"use client";
import "./globals.css";
import Menu from "@/app/components/Menu/Menu";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Menu></Menu>
        {children}
      </body>
    </html>
  );
}
